# Generated by Django 5.1 on 2024-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату производства",
                null=True,
                verbose_name="Дата производства",
            ),
        ),
    ]
